CREATE TABLE `PLAN` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`NAME` varchar(50) NOT NULL,
	`ROI_DATA` varchar(50) NOT NULL,
	`ROI_FREE_CALL` varchar(50) NOT NULL,
	`ROI_FREE_TEXT` varchar(50) NOT NULL,
	`EU_DATA` varchar(50) NOT NULL,
	`EU_FREE_CALL` varchar(50) NOT NULL DEFAULT 'Unlimited',
	`EU_FREE_TEXT` varchar(50) NOT NULL DEFAULT 'Unlimited',
	`EU_ROAMIMG` varchar(50) NOT NULL,
	`UK_DATA` varchar(50) NOT NULL,
	`UK_FREE_CALL` varchar(50) NOT NULL,
	`UK_FREE_TEXT` varchar(50) NOT NULL,
	`INT_DATA` varchar(50) NOT NULL,
	`INT_FREE_CALL` varchar(50) NOT NULL,
	`INT_FREE_TEXT` varchar(50) NOT NULL,
	`CANADA_ROAMIMG` varchar(50) NOT NULL,
	`USA_ROAMIMG` varchar(50) NOT NULL,
	`REWARD` varchar(250) NOT NULL,
	`CONTRACT` varchar(50) NOT NULL,
	`DISCOUNT` varchar(250) NOT NULL,
	`DESC` varchar(250) NOT NULL,
	`PRICE` INT NOT NULL,
	`PRICE_CURR` varchar(10) NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `PHONE` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`NAME` varchar(50) NOT NULL,
	`MODEL` varchar(50) NOT NULL,
	`MEMORY` varchar(50) NOT NULL,
	`STORAGE` varchar(50) NOT NULL,
	`COLOR` varchar(50) NOT NULL,
	`NETWORK` varchar(50) NOT NULL,
	`DISPLAY` varchar(50) NOT NULL,
	`MAIN_CAMERA` varchar(50) NOT NULL,
	`FRONT_CAMERA` varchar(50) NOT NULL,
	`OS` varchar(50) NOT NULL,
	`PRICE` INT(10) NOT NULL,
	`PRICE_CURR` varchar(10) NOT NULL,
	`DESC` varchar(250) NOT NULL,
	`IMAGE` blob NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `ACCESSORY` (
	`ID` INT(10) NOT NULL,
	`NAME` varchar(50) NOT NULL,
	`DESC` varchar(250) NOT NULL,
	`PRICE` INT(10) NOT NULL,
	`PRICE_CURR` varchar(10) NOT NULL,
	`IMAGE` blob NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `OFFER` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`NAME` varchar(50) NOT NULL,
	`DESC` varchar(250) NOT NULL,
	`VALUE_PERC` INT NOT NULL,
	`VALUE_FIXED` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `CUSTOMER` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`PLAN_ID` INT(10) NOT NULL,
	`FIRST_NAME` varchar(50) NOT NULL,
	`MIDDLE_NAME` varchar(50) NOT NULL,
	`SECOND_NAME` varchar(50) NOT NULL,
	`ADDRESS1` varchar(250) NOT NULL,
	`ADDRESS2` varchar(250) NOT NULL,
	`ADDRESS3` varchar(250) NOT NULL,
	`COUNTY` varchar(250) NOT NULL,
	`COUNTRY` varchar(250) NOT NULL,
	`PLAN_START` DATETIME NOT NULL,
	`PLAN_END` DATETIME NOT NULL,
	`HOME_PHONE` VARCHAR(50) NOT NULL,
	`MOBILE_PHONE` VARCHAR(50) NOT NULL,
	`EMAIL1` VARCHAR(50) NOT NULL,
	`EMAIL2` VARCHAR(50) NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `USER` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`LOGIN` varchar(50) NOT NULL,
	`PASSWORD` varchar(50) NOT NULL,
	`CREATE` BOOLEAN NOT NULL,
	`READ` BOOLEAN NOT NULL,
	`UPDATE` BOOLEAN NOT NULL,
	`DEACTIVE` BOOLEAN NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `PLAN_PHONE` (
	`PLAN_ID` INT(10) NOT NULL,
	`PHONE_ID` INT(10) NOT NULL
);

CREATE TABLE `PHONE_ACCESSORY` (
	`PHONE_ID` INT(10) NOT NULL,
	`ACCESSORY_ID` INT(10) NOT NULL
);

CREATE TABLE `PLAN_OFFER` (
	`PLAN_ID` INT(10) NOT NULL,
	`OFFER_ID` INT(10) NOT NULL
);

CREATE TABLE `INVOICE` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`NAME` varchar(50) NOT NULL,
	`PLAN_ID` INT(10) NOT NULL,
	`CUST_ID` INT(10) NOT NULL,
	`CREATED_DT` TIMESTAMP NOT NULL,
	`UPDATED_DT` TIMESTAMP NOT NULL,
	`DISCOUNT` INT NOT NULL,
	`TOTAL_AMT` INT NOT NULL,
	`VALUE` INT NOT NULL,
	`PAY_METHOD` varchar(50) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `DOCUMENT` (
	`ID` INT(10) NOT NULL,
	`CUST_ID` INT(10) NOT NULL,
	`MOB_CONTRACT` blob NOT NULL,
	`SEPA_DD` blob NOT NULL,
	`INS_CONTRACT` blob NOT NULL,
	`FUND_CONTRACT` blob NOT NULL,
	PRIMARY KEY (`ID`)
);

ALTER TABLE `CUSTOMER` ADD CONSTRAINT `CUSTOMER_fk0` FOREIGN KEY (`PLAN_ID`) REFERENCES `PLAN`(`ID`);

ALTER TABLE `PLAN_PHONE` ADD CONSTRAINT `PLAN_PHONE_fk0` FOREIGN KEY (`PLAN_ID`) REFERENCES `PLAN`(`ID`);

ALTER TABLE `PLAN_PHONE` ADD CONSTRAINT `PLAN_PHONE_fk1` FOREIGN KEY (`PHONE_ID`) REFERENCES `PHONE`(`ID`);

ALTER TABLE `PHONE_ACCESSORY` ADD CONSTRAINT `PHONE_ACCESSORY_fk0` FOREIGN KEY (`PHONE_ID`) REFERENCES `PHONE`(`ID`);

ALTER TABLE `PHONE_ACCESSORY` ADD CONSTRAINT `PHONE_ACCESSORY_fk1` FOREIGN KEY (`ACCESSORY_ID`) REFERENCES `ACCESSORY`(`ID`);

ALTER TABLE `PLAN_OFFER` ADD CONSTRAINT `PLAN_OFFER_fk0` FOREIGN KEY (`PLAN_ID`) REFERENCES `PLAN`(`ID`);

ALTER TABLE `PLAN_OFFER` ADD CONSTRAINT `PLAN_OFFER_fk1` FOREIGN KEY (`OFFER_ID`) REFERENCES `OFFER`(`ID`);

ALTER TABLE `INVOICE` ADD CONSTRAINT `INVOICE_fk0` FOREIGN KEY (`PLAN_ID`) REFERENCES `PLAN`(`ID`);

ALTER TABLE `INVOICE` ADD CONSTRAINT `INVOICE_fk1` FOREIGN KEY (`CUST_ID`) REFERENCES `CUSTOMER`(`ID`);

ALTER TABLE `DOCUMENT` ADD CONSTRAINT `DOCUMENT_fk0` FOREIGN KEY (`CUST_ID`) REFERENCES `CUSTOMER`(`ID`);

